version: "3.9"

services:
  dynmao_local:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"

  minio:
    image: quay.io/minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio1234
      MINIO_ROOT_PASSWORD: minio1234

  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minio1234 minio1234;
      /usr/bin/mc mb myminio/stability-ai;
      /usr/bin/mc policy set public myminio/stability-ai;
      exit 0;
      "