// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/balance": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "credit"
                ],
                "summary": "stability.ai 잔여 크레딧 조회",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BalanceResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BaseErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BaseErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/generate/{engineId}": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "이미지 생성하기",
                "parameters": [
                    {
                        "enum": [
                            "stable-diffusion-512-v2-1",
                            "stable-diffusion-512-v2-0",
                            "stable-diffusion-v1-5"
                        ],
                        "type": "string",
                        "description": "엔진 ID",
                        "name": "engineId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "상세는 아래 Model 클릭해서 정보 확인",
                        "name": "GenerateInput",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/stability_ai.GenerateInput"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/stability_ai.Image"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BaseErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BaseErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/image": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "이미지 리스트 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "(Optional) keyword로 조건 검색",
                        "name": "keyword",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/stability_ai.Image"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BaseErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BaseErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/image/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "image"
                ],
                "summary": "ID로 이미지 조회",
                "parameters": [
                    {
                        "type": "string",
                        "description": "image의 uuid",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.Image"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BaseErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/stability_ai.BaseErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "stability_ai.BalanceResponse": {
            "type": "object",
            "properties": {
                "credits": {
                    "type": "number"
                }
            }
        },
        "stability_ai.BaseErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "stability_ai.GenerateInput": {
            "type": "object",
            "required": [
                "cfg_scale",
                "clip_guidance_preset",
                "height",
                "samples",
                "steps",
                "text_prompts",
                "width"
            ],
            "properties": {
                "cfg_scale": {
                    "description": "확산 프로세스가 프롬프트 텍스트에 얼마나 엄격하게 적용되는지 (값이 높을수록 이미지가 프롬프트에 더 가깝게 유지됨)",
                    "type": "integer",
                    "default": 7,
                    "maximum": 35,
                    "minimum": 0
                },
                "clip_guidance_preset": {
                    "type": "string",
                    "enum": [
                        "FAST_BLUE",
                        "FAST_GREEN",
                        "NONE",
                        "SIMPLE",
                        "SLOW",
                        "SLOWER",
                        "SLOWEST"
                    ]
                },
                "height": {
                    "type": "integer",
                    "default": 512,
                    "maximum": 2048,
                    "minimum": 512
                },
                "samples": {
                    "description": "생성할 이미지 수",
                    "type": "integer",
                    "default": 1,
                    "maximum": 10,
                    "minimum": 1
                },
                "steps": {
                    "description": "실행할 확산 단계 수. 이미지 품질에 영향 큼. 비용에도 영향 큼.",
                    "type": "integer",
                    "default": 40,
                    "maximum": 150,
                    "minimum": 10
                },
                "style": {
                    "description": "개발 중. 생략해도 됨",
                    "type": "string"
                },
                "text_prompts": {
                    "type": "string"
                },
                "width": {
                    "type": "integer",
                    "default": 512,
                    "maximum": 2048,
                    "minimum": 512
                }
            }
        },
        "stability_ai.Image": {
            "type": "object",
            "properties": {
                "imageID": {
                    "description": "이미지 고유 ID",
                    "type": "string"
                },
                "keywords": {
                    "description": "이미지의 키워드 (프롬프트에서 추출)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "requestInfo": {
                    "description": "이미지 생성 요청값",
                    "$ref": "#/definitions/stability_ai.StabilityApiPayload"
                },
                "time": {
                    "type": "string"
                },
                "url": {
                    "description": "이미지 URL",
                    "type": "string"
                }
            }
        },
        "stability_ai.StabilityApiPayload": {
            "type": "object",
            "required": [
                "cfg_scale",
                "samples",
                "text_prompts"
            ],
            "properties": {
                "cfg_scale": {
                    "type": "integer"
                },
                "clip_guidance_preset": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "samples": {
                    "type": "integer"
                },
                "steps": {
                    "type": "integer"
                },
                "text_prompts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/stability_ai.TextPrompt"
                    }
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "stability_ai.TextPrompt": {
            "type": "object",
            "properties": {
                "text": {
                    "type": "string"
                },
                "weight": {
                    "type": "integer",
                    "default": 1
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
